### ISSUE TITLE
Crash with Collector's Reap Mod

### ISSUE THREAD

**Issue by ghost** [Catscythe-Corner/Seasonals#2]
Hi, I've updated seasonals to 4.1.0 but my game crashed and I speculate that it is because of an incompatibility with collector's reap mod which is a mod that expands Farmers Delight along with Seasonals.

There's the crash report file.
[crash-2023-08-17_15.16.02-client.txt](https://github.com/Catscythe-Corner/Seasonals/files/12373067/crash-2023-08-17_15.16.02-client.txt)

I hope there is a solution.
I appreciate the feedback.

**Comment by Uraneptus** [comment]
Hey, thanks for reporting this. Unfortunately I cannot fix this problem on my end. I will look into fixing the problem on the end of the collector's reap mod

**Comment by Uraneptus** [comment]
[this](https://github.com/brnbrd/CollectorsReap/pull/19) PR should fix the issue. You'll have to wait until the collector's reap dev merges this PR tho!
